### ISSUE TITLE
Publish to the official plugin repository

### ISSUE THREAD

**Issue by remal** [AntoniRokitnicki/AdvancedExpressionFolding#30]
Hello,

Thanks for working on the plugin!

Is there a chance it will be published to the official plugin repository?

**Comment by AntoniRokitnicki** [comment]
![Screenshot 2024-01-25 at 22 41 10](https://github.com/AntoniRokitnicki/AdvancedExpressionFolding/assets/3055326/691344b2-338b-4311-a007-b12f35f7bce6)

in progress

**Comment by AntoniRokitnicki** [comment]
https://plugins.jetbrains.com/plugin/23659-advanced-java-folding-2-fork-
